name: Build
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'If we should publish a new build'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  workflow_call:
    inputs:
      publish:
        description: 'If we should publish a new build'
        default: 'false'
        required: false
        type: string
  push:
    branches: [ ver/1.19.2 ]
    paths-ignore:  [ '*.md', '*.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1.0.5

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            patches:
              - 'patches/**'

      - name: Publish
        if: ${{ inputs.publish == 'true' || github.event.before != '' && steps.changes.outputs.patches == 'true' }}
        run: |
          ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}
          ./gradlew createReobfPaperclipJar
          mv build/libs/tentacles-paperclip-1.19.2-R0.1-SNAPSHOT-reobf.jar tentacles-1.19.2.jar
          gh release create "v1.19.2-${{ github.run_number }}" -t "Release 1.19.2-${{ github.run_number }}" tentacles-1.19.2.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
