name: Build
on:
  push:
    branches: [ ver/1.18.1 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Publish
        run: |
          ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}
          ./gradlew createReobfPaperclipJar
          mv build/libs/tentacles-paperclip-1.18.1-R0.1-SNAPSHOT-reobf.jar tentacles-1.18.1-${{ github.run_number }}.jar
          gh release create "v1.18.1-${{ github.run_number }}" -t "Release 1.18.1-${{ github.run_number }}" tentacles-1.18.1-${{ github.run_number }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}