name: Upstream
on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  upstream:
    runs-on: ubuntu-latest
    outputs:
      patches: ${{ steps.changes.outputs.patches }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Update upstream
        run: |
          ./scripts/updateUpstream.sh
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            patches:
              - 'patches/**'

  callworkflow:
    needs: upstream
    if: ${{ needs.upstream.outputs.patches == 'true' }}
    uses: DaRacci/Tentacles/.github/workflows/build.yml@ver/1.19.2
    with:
      publish: 'true'
